import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import Cookies from "js-cookie";

// Define the interface for AuthState to represent the authentication state
export interface AuthState {
  isAuthenticated: boolean;
  isAdmin: boolean | undefined;
  token: string | undefined;
  theme: 'light' | 'dark';
}

// Initial state of the authentication slice
const initialState: AuthState = {
  isAuthenticated: !!Cookies.get("token"),
  isAdmin: Cookies.get("useradmin") === "true",
  token: Cookies.get("token"),
  theme: (Cookies.get("theme") as 'light' | 'dark') || 'light',
};

// Define the type of payload for the login action
interface LoginPayload {
  token: string;
  isAdmin: boolean;
}

// Create the authSlice using createSlice from Redux Toolkit
export const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    login: (state: AuthState, action: PayloadAction<LoginPayload>) => {
      state.isAuthenticated = true;
      state.isAdmin = action.payload.isAdmin;
      state.token = action.payload.token;
      Cookies.set("token", action.payload.token);
      Cookies.set("useradmin", action.payload.isAdmin.toString());
    },
    logout: (state: AuthState) => {
      state.isAuthenticated = false;
      state.token = undefined;
      state.isAdmin = undefined;
      Cookies.remove("token");
      Cookies.remove("useradmin");
    },
    setTheme: (state: AuthState, action: PayloadAction<'light' | 'dark'>) => {
      state.theme = action.payload;
      Cookies.set("theme", action.payload);
    },
  },
});

// Export the actions and reducer generated by createSlice
export const { login, logout, setTheme } = authSlice.actions;

// Selectors to access parts of the state
export const selectAuth = (state: { auth: AuthState }) => state.auth;
export const selectTheme = (state: { auth: AuthState }) => state.auth.theme;

// Export the reducer function to be used with Redux store
export default authSlice.reducer;
